notas =[8,9,7,6]
notas.pop()
console.log(notas)
notas.push(9.5)
console.log(notas)
notas.pop()
console.log(notas)
notas.pop()
console.log(notas.pop())
notas.push(8)
console.log(notas)
notas.push(7.5)
console.log(notas)