Clinica=[];
console.log("Fila de espera vazia:", Clinica);
Clinica.push("Pastor Alemão", "Pastor Belga", "Labrador");
console.log("Chegada de três animais a fila de recepção:", Clinica);
Clinica.pop("Pastor Alemão");
console.log("Remoção", Clinicap);
Clinica.pop("Pastor Belga");
console.log("Remoção:",Clinica);
Clinica.pop("Labrador");
console.log("Remoção", Clinica);
console.log("Fila de espera vazia: ", Clinica);